---
title: "Context-Dependent Benchmarks for Ecological Typology Biovalidity Assessment"
author: Jonathan F. Jupke
bibliography: "C:/Users/jonjupke/Zotero/MyLibrary.bib"
csl: ecotoxicology.csl
output: 
        bookdown::word_document2: 
                reference_docx: template.docx
nocite: |
  @panagosGlobalRainfallErosivity2023, @panagosEuropeanSoilData2022, @witjesEcodatacubeEuAnalysisready2023, @amatulliHydrography90mNewHighresolution2022, @amatulliGeomorpho90mEmpiricalEvaluation2020, @eeaPotentialFloodproneArea2020,@bergHydrologyRelatedClimate2021, @tothNewGenerationHydraulic2015, @linkeGlobalHydroenvironmentalSubbasin2019, @eeaEUHydroRiverNetwork2019, @messagerEstimatingVolumeAge2016, @rgiconsortiumRandolphGlacierInventory2017, @brunCHELSABIOCLIMNovelSet2022, @cornuDistributionGroundwaterHabitats2013               
---

```{r libraries, echo=FALSE, results='hide', message=FALSE}
library(knitr)
library(data.table)
library(flextable)
library(bookdown)
suppressPackageStartupMessages(library(dplyr)) 
ss <- readRDS("../summary_statistics.rds")
```

```{r index_table_env_create, echo=FALSE}
# Create the data frame
dat <- tibble(
  Variable = c(
    "Rainfall erosivity",
    "Soil Organic Carbon",
    "Soil pH in Water",
    "Slope",
    "Roughness",
    "Floodplain Area",
    "Mean annual discharge",
    "Minimum annual discharge",
    "Saturated Soil Water Content",
    "Upstream catchment area",
    "Maximum annual discharge",
    "Snow Cover",
    "Segment Sinuosity",
    "Mean Valley Bottom Flatness Index",
    "Maximum Valley Bottom Flatness Index",
    "Mean Stream Power Index",
    "Maximum Stream Power Index",
    "Lake Index",
    "Elevation",
    "Groundwater Table Depth",
    "Glaciated Area in Catchment",
    "Precipitation of Wettest Month",
    "Precipitation of Driest Month",
    "Minimum Temperature Coldest Month",
    "Maximum Temperature Warmest Month",
    "Bedrock Geology",
    "Catchment soil type"
  ),
  #`Spatial Scale` = c(
  #  rep("Ecosystem", 16),
   # "Region, Ecosystem",
  #  rep("Region", 8)
 # ),
  `Data product` = c(
    "GloREDa",
    "European Soil Database v2.0",
    "EcoDataCube",
    "Hydrography90m",
    "Geomorpho90m",
    "Potential Flood prone Area",
    "Copernicus C3S",
    "Copernicus C3S",
    "Soil Hydraulic Properties",
    "HydroATLAS",
    "Copernicus C3S",
    "HydroATLAS",
    "EU Hydro",
    "EcoDataCube",
    "EcoDataCube",
    "Hydrography90m",
    "Hydrography90m",
    "HydroLAKES",
    "Hydrography90m",
    "HydroATLAS",
    "Randolph Glacier Inventory",
    "CHELSA-BIOCLIM+",
    "CHELSA-BIOCLIM+",
    "CHELSA-BIOCLIM+",
    "CHELSA-BIOCLIM+",
    "IHME",
    "European Soil Database v2.0"
  ),
  Reference = c(
    "Panagos et al. (2023)",
    "Panagos et al. (2022)",
    "Witjes et al. (2023)",
    "Amatulli et al. (2022)",
    "Amatulli et al. (2020)",
    "EEA (2020)",
    "Berg et al. (2021)",
    "Berg et al. (2021)",
    "Tóth et al. (2015)",
    "Linke et al (2019)",
    "Berg et al. (2021)",
    "Linke et al (2019)",
    "EEA (2019)",
    "Witjes et al. (2023)",
    "Witjes et al. (2023)",
    "Amatulli et al. (2022)",
    "Amatulli et al. (2022)",
    "Messager et al. (2016)",
    "Amatulli et al. (2022)",
    "Linke et al. (2019)",
    "RGI Consortium (2017)",
    "Brun et al. (2022)",
    "Brun et al. (2022)",
    "Brun et al. (2022)",
    "Brun et al. (2022)",
    "Cornu et al. (2013)",
    "Panagos et al. (2022)"
  )
)

# Create and format the flextable
ft <- dat %>%
  flextable() %>%
  theme_vanilla() %>%
  fontsize(size = 10) %>%
  autofit() %>%
  align(align = "left", part = "all") %>%
  border_outer(part = "all") %>%
  border_inner_h(part = "all") %>%
  border_inner_v(part = "all") %>%
  set_table_properties(layout = "autofit") %>% 
        set_caption("Environmental variables used to fit and simulate from Hmsc models")

# Add some padding and set header style
ft <- ft %>%
  padding(padding = 4, part = "all") %>%
  bold(part = "header")
```

```{r child='01_abstract.rmd', eval=T}
```

```{r child='02_introduction.rmd', eval=T}
```

```{r child='03_methods.rmd', eval=T}
```

```{r child='supplementary_5_metrics.rmd', eval=T}
```

```{r child='supplementary_ppc.Rmd', eval=T}
```

```{r child='supplement_notation.Rmd', eval=T}
```

# Acknowledgements

# References